-- Cleaned and ordered script generated automatically
-- Purpose: ensure valid INSERT order and fix common issues (quoted NULLs and unescaped apostrophes)
-- Encoding
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Database
CREATE DATABASE IF NOT EXISTS MovieDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE MovieDB;

-- (Re)create tables with safe options
DROP TABLE IF EXISTS movie_actors;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS actors;
DROP TABLE IF EXISTS directors;

CREATE TABLE IF NOT EXISTS directors (
    director_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    birthdate DATE,
    nationality VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS actors (
    actor_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    birthdate DATE,
    nationality VARCHAR(100),
    photo LONGBLOB
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS movies (
    movie_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    release_year YEAR,
    genre VARCHAR(100),
    director_id INT,
    CONSTRAINT fk_movies_director FOREIGN KEY (director_id) REFERENCES directors(director_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS movie_actors (
    movie_id INT,
    actor_id INT,
    role VARCHAR(255),
    PRIMARY KEY (movie_id, actor_id),
    CONSTRAINT fk_ma_movie FOREIGN KEY (movie_id) REFERENCES movies(movie_id) ON DELETE CASCADE,
    CONSTRAINT fk_ma_actor FOREIGN KEY (actor_id) REFERENCES actors(actor_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Data loads (directors -> actors -> movies -> movie_actors)

-- Directors
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);
        INSERT INTO directors (name, birthdate, nationality);

-- Actors
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);
        INSERT INTO actors (name, birthdate, nationality, photo);

-- Movies
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);
        INSERT INTO movies (title, release_year, genre, director_id);

-- Movie-Actors
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);
            INSERT INTO movie_actors (movie_id, actor_id, role);

SET FOREIGN_KEY_CHECKS = 1;
